apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-heroes-quarkus-super-heroes-u3pr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-heroes-quarkus-super-heroes-u3pr
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-heroes-quarkus-superrzlk
spec:
  path: /
  port:
    targetPort: 8083
  to:
    kind: Service
    name: rest-heroes-quarkus-super-heroes-u3pr
    weight: null
status: {}
