apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-villains-quarkus-super-heroes-ofm8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-villains-quarkus-super-heroes-ofm8
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-villains-quarkus-super-heroes-ofm8
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rest-villains-quarkus-super-heroes-ofm8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rest-villains-quarkus-super-heroes-ofm8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/quarkus-super-heroes/rest-villains-quarkus-super-heroes-ofm8@sha256:a6b01b4e7ed75e34c2b157bff00d9e5e46ac46a2a746eb01827316794b55f63d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8084
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
