apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-villains-quarkus-super-heroes-ofm8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-villains-quarkus-super-heroes-ofm8
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-villains-quarkus-super-heroes-ofm8
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    app.kubernetes.io/instance: rest-villains-quarkus-super-heroes-ofm8
status:
  loadBalancer: {}
