apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ui-super-heroes-quarkus-super-heroes-tpwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ui-super-heroes-quarkus-super-heroes-tpwz
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: ui-super-heroes-quarkus-super-heroes-tpwz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ui-super-heroes-quarkus-super-heroes-tpwz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ui-super-heroes-quarkus-super-heroes-tpwz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/quarkus-super-heroes/ui-super-heroes-quarkus-super-heroes-tpwz@sha256:8e9b84e310ff5aa362e6f6d16730ac84736732c542fcf61d52c11592789b6cae
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
