apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ui-super-heroes-quarkus-super-heroes-tpwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ui-super-heroes-quarkus-super-heroes-tpwz
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: ui-super-heroes-quarkus-super-heroes-tpwz
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ui-super-heroes-quarkus-super-heroes-tpwz
status:
  loadBalancer: {}
