apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: event-statistics-quarkus-super-heroes-6t3l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: event-statistics-quarkus-super-heroes-6t3l
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: event-statistics-quarkus-super-heroes-6t3l
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    app.kubernetes.io/instance: event-statistics-quarkus-super-heroes-6t3l
status:
  loadBalancer: {}
