apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-heroes-quarkus-super-heroes-u3pr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-heroes-quarkus-super-heroes-u3pr
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-heroes-quarkus-super-heroes-u3pr
spec:
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/instance: rest-heroes-quarkus-super-heroes-u3pr
status:
  loadBalancer: {}
