apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rest-villains-quarkus-super-heroes-ofm8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/quarkus-super-heroes/rest-villains-quarkus-super-heroes-ofm8@sha256:a6b01b4e7ed75e34c2b157bff00d9e5e46ac46a2a746eb01827316794b55f63d
        name: my-java-quarkus
        resources: {}
status: {}
