apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-fights-quarkus-super3yi0
spec:
  path: /
  port:
    targetPort: 8082
  to:
    kind: Service
    name: rest-fights-quarkus-super-heroes-yca7
    weight: null
status: {}
