apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-fights-quarkus-super-heroes-yca7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/quarkus-super-heroes/rest-fights-quarkus-super-heroes-yca7@sha256:71d733421953d0d8fbd0e70f3258d2c4eda94191d4356b1d01591b20cdccadfe
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8082
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
