apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-fights-quarkus-super-heroes-yca7
    app.kubernetes.io/part-of: quarkus-super-heroes
  name: rest-fights-quarkus-super-heroes-yca7
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app.kubernetes.io/instance: rest-fights-quarkus-super-heroes-yca7
status:
  loadBalancer: {}
